
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "test player",
    "username": "test player",
    "password": "asdasd"
}

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "TestPlayer",
    "password": "asdasd"
}

###
GET http://localhost:8000/auth/get-user/eyJhbGciOiJIUzI1NiJ9.OQ.rABojY9ZAU6Q7uYs4tyoU1IWUvFiFX2sMjZWDQ6CoII

###
POST http://localhost:8000/gameplay/save-game/active
Content-Type: application/json

{
    "username": "test"
}
